package ArduinoML.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_1933305387245017213(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x76e4e660653879ccL, "init_state")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_8567225692854946391(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5586951442585418050(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_8558568122170875679(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cfdL, 0x34af21048778d78fL, "rows"));
  }
  public static Object propertyMacro_GetPropertyValue_8558568122170975795(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cfdL, 0x34af21048778d791L, "cols"));
  }
  public static Object propertyMacro_GetPropertyValue_4529363332655246350(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, 0x10d34f97574L, "shortDescription"));
  }
  public static Object propertyMacro_GetPropertyValue_8558568122170764696(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0xc61abad160dc650L, 0xc61abad160dc651L, "sensor")), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_8558568122170787859(final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0xc61abad160dc650L, 0xc61abad160dc651L, "sensor")), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe6L, 0x3edb87f415993e29L, "type"), "digital");
  }
  public static Object propertyMacro_GetPropertyValue_8558568122170782269(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0xc61abad160dc650L, 0xc61abad160dc651L, "sensor")), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_4529363332655474181(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL, 0x3edb87f41598da6bL, "target")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_1996913459656508903(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x1bb676362203e775L, 0x1bb676362203e7b7L, "sensor")), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_1996913459656511029(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x1bb676362203e775L, 0x1bb676362203e791L, "status"), null) ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_1996913459656516634(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL, 0x3edb87f41598da6bL, "target")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_1996913459656538296(final PropertyMacroContext _context) {
    return _context.getSessionObject("current_state_name") + "";
  }
  public static Object propertyMacro_GetPropertyValue_1996913459656371598(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L, 0x76e4e6606536afe3L, "pin"));
  }
  public static Iterable<SNode> sourceNodesQuery_8567225692854966596(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x76e4e6606536afeaL, "bricks"));
  }
  public static Iterable<SNode> sourceNodesQuery_5956817795874746387(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x34af210487785ceeL, "bus_bricks"));
  }
  public static Iterable<SNode> sourceNodesQuery_5586951442585498561(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L, 0x76e4e660653879c9L, "states"));
  }
  public static Iterable<SNode> sourceNodesQuery_3229986099360090727(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L, 0x2cd3373e81c97b44L, "actions"));
  }
  public static Iterable<SNode> sourceNodesQuery_3229986099360080115(final SourceSubstituteMacroNodesContext _context) {
    _context.putSessionObject("current_state_name", SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L, 0x2cd3373e81cc204cL, "transitions"));
  }
}
