package ArduinoML.sandbox;

/*Generated by MPS */


public class map_App {

  public static void main(String[] args) {
    System.out.println("//Code generated by ArduinoML");
    System.out.println("#include <LiquidCrystal.h>\n\n// these constants won't change.  But you can change the size of your LCD using them:\nint numRows;\nint numCols;\nint pos = 0;\n\n// Delay between each row print\nconst int wait = 1000;\n");
    System.out.println("LiquidCrystal lcd(10, 11, 12, 13, 14, 15, 16);\n");

    System.out.println("void setup() {");
    System.out.println("  pinMode(" + 8 + ", INPUT);");
    System.out.println("  pinMode(" + 2 + ", INPUT);");
    System.out.println("  numRows = " + 2 + ";");
    System.out.println("  numCols = " + 16 + ";");
    System.out.println("  lcd.begin(numCols, numRows);");
    System.out.println("}");

    System.out.println("\n// Behavorial concepts");

    System.out.println("long value = 0;\n");

    System.out.println("// Here comes the states declarations");
    System.out.print("void state_" + "read" + "() {\n");
    if ("analog" == "digital") {
      System.out.println("  value = (long) digitalRead(" + 2 + ");");
    } else {
      System.out.println("  value = (long) analogRead(" + 2 + ");");
    }
    System.out.println("  state_" + "write" + "();");
    System.out.println("}\n");
    System.out.print("void state_" + "write" + "() {\n");
    System.out.print("  char val[30];\n  char text[] = \"");
    System.out.println("La temperature est de : " + "\";");
    System.out.println("  sprintf(val, \"%ld\", value);");
    System.out.println("  char finalString[sizeof(text) + sizeof(value)];");
    System.out.println("  strcpy(finalString, text);\n  strcat(finalString, val);\n  for(int row = 0; row < numRows; row++) {");
    System.out.println("    for(int col = 0; col < numCols; col++) {");
    System.out.println("      // set the cursor position:\n      lcd.setCursor(col, row);\n      // print the letter:\n      lcd.write(finalString[pos++]);\n      if(pos > sizeof(finalString)) {\n        exit(0);\n      }\n    }\n    delay(wait);\n  }");
    System.out.println("  lcd.clear();\n  pos -= numCols;");
    System.out.println("  state_" + "read" + "();");
    System.out.println("}\n");

    System.out.println("\nvoid loop() { state_" + "read" + "(); } // Entering init state\n");
  }
}
