package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum SensorType {
  digital("digital", "digital"),
  analog("analog", "analog");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  SensorType(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<SensorType> getConstants() {
    List<SensorType> list = ListSequence.fromList(new LinkedList<SensorType>());
    ListSequence.fromList(list).addElement(SensorType.digital);
    ListSequence.fromList(list).addElement(SensorType.analog);
    return list;
  }
  public static SensorType getDefault() {
    return SensorType.digital;
  }
  public static SensorType parseValue(String value) {
    if (value == null) {
      return SensorType.getDefault();
    }
    if (value.equals(SensorType.digital.getValueAsString())) {
      return SensorType.digital;
    }
    if (value.equals(SensorType.analog.getValueAsString())) {
      return SensorType.analog;
    }
    return SensorType.getDefault();
  }
}
