package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAction = new ConceptDescriptorBuilder("ArduinoML.structure.Action", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptActuator = new ConceptDescriptorBuilder("ArduinoML.structure.Actuator", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x1bb67636220392e2L)).super_("ArduinoML.structure.Brick").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).parents("ArduinoML.structure.Brick").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).create();
  /*package*/ final ConceptDescriptor myConceptApp = new ConceptDescriptorBuilder("ArduinoML.structure.App", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe7L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.execution.util.structure.IMainClass", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(8567225692854974924L, "init_state", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L), false)).references("init_state").childDescriptors(new ConceptDescriptorBuilder.Link(3796289314233015534L, "bus_bricks", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cccL), true, true, false), new ConceptDescriptorBuilder.Link(8567225692854857706L, "bricks", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L), false, true, false), new ConceptDescriptorBuilder.Link(8567225692854974921L, "states", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L), false, true, false)).children(new String[]{"bus_bricks", "bricks", "states"}, new boolean[]{true, true, true}).create();
  /*package*/ final ConceptDescriptor myConceptBrick = new ConceptDescriptorBuilder("ArduinoML.structure.Brick", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8567225692854857699L, "pin")).properties("pin").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptBusBrick = new ConceptDescriptorBuilder("ArduinoML.structure.BusBrick", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cccL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(3796289314233015532L, "bus")).properties("bus").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptConditionalTransition = new ConceptDescriptorBuilder("ArduinoML.structure.ConditionalTransition", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x1bb676362203e775L)).super_("ArduinoML.structure.Transition").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL)).parents("ArduinoML.structure.Transition").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1996913459656386449L, "status")).properties("status").referenceDescriptors(new ConceptDescriptorBuilder.Ref(1996913459656386487L, "sensor", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe6L), false)).references("sensor").create();
  /*package*/ final ConceptDescriptor myConceptConverter = new ConceptDescriptorBuilder("ArduinoML.structure.Converter", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x4ea55364cad324e5L)).super_("ArduinoML.structure.Action").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).parents("ArduinoML.structure.Action").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5667027398480307513L, "from"), new ConceptDescriptorBuilder.Prop(5667027398480307573L, "to")).properties("from", "to").create();
  /*package*/ final ConceptDescriptor myConceptGoto = new ConceptDescriptorBuilder("ArduinoML.structure.Goto", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x1bb676362203e759L)).super_("ArduinoML.structure.Transition").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL)).parents("ArduinoML.structure.Transition").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL)).create();
  /*package*/ final ConceptDescriptor myConceptLCDScreen = new ConceptDescriptorBuilder("ArduinoML.structure.LCDScreen", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cfdL)).super_("ArduinoML.structure.BusBrick").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cccL)).parents("ArduinoML.structure.BusBrick").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cccL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(3796289314233046927L, "rows"), new ConceptDescriptorBuilder.Prop(3796289314233046929L, "cols")).properties("rows", "cols").create();
  /*package*/ final ConceptDescriptor myConceptReadValue = new ConceptDescriptorBuilder("ArduinoML.structure.ReadValue", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0xc61abad160dc650L)).super_("ArduinoML.structure.Action").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).parents("ArduinoML.structure.Action").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(892182961083762257L, "sensor", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe6L), false)).references("sensor").create();
  /*package*/ final ConceptDescriptor myConceptSensor = new ConceptDescriptorBuilder("ArduinoML.structure.Sensor", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe6L)).super_("ArduinoML.structure.Brick").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).parents("ArduinoML.structure.Brick").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e6606536afe0L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4529363332655300137L, "type")).properties("type").create();
  /*package*/ final ConceptDescriptor myConceptState = new ConceptDescriptorBuilder("ArduinoML.structure.State", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(3229986099359742788L, "actions", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L), true, true, false), new ConceptDescriptorBuilder.Link(3229986099359916108L, "transitions", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL), true, true, false)).children(new String[]{"actions", "transitions"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptTransition = new ConceptDescriptorBuilder("ArduinoML.structure.Transition", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f41598da6aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4529363332655274603L, "target", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x76e4e66065386d30L), false)).references("target").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptWriteValue = new ConceptDescriptorBuilder("ArduinoML.structure.WriteValue", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x3edb87f415957f0dL)).super_("ArduinoML.structure.Action").super_(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).parents("ArduinoML.structure.Action").parentIds(MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x2cd3373e81c97b43L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4529363332655054610L, "screen", MetaIdFactory.conceptId(0x3389428e8c9944b6L, 0x8b7e9adb09b40a0bL, 0x34af210487785cfdL), false)).references("screen").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptApp, myConceptBrick, myConceptBusBrick, myConceptConditionalTransition, myConceptConverter, myConceptGoto, myConceptLCDScreen, myConceptReadValue, myConceptSensor, myConceptState, myConceptTransition, myConceptWriteValue);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0s, conceptFqName)) {
      case 0:
        return myConceptAction;
      case 1:
        return myConceptActuator;
      case 2:
        return myConceptApp;
      case 3:
        return myConceptBrick;
      case 4:
        return myConceptBusBrick;
      case 5:
        return myConceptConditionalTransition;
      case 6:
        return myConceptConverter;
      case 7:
        return myConceptGoto;
      case 8:
        return myConceptLCDScreen;
      case 9:
        return myConceptReadValue;
      case 10:
        return myConceptSensor;
      case 11:
        return myConceptState;
      case 12:
        return myConceptTransition;
      case 13:
        return myConceptWriteValue;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0s = new String[]{"ArduinoML.structure.Action", "ArduinoML.structure.Actuator", "ArduinoML.structure.App", "ArduinoML.structure.Brick", "ArduinoML.structure.BusBrick", "ArduinoML.structure.ConditionalTransition", "ArduinoML.structure.Converter", "ArduinoML.structure.Goto", "ArduinoML.structure.LCDScreen", "ArduinoML.structure.ReadValue", "ArduinoML.structure.Sensor", "ArduinoML.structure.State", "ArduinoML.structure.Transition", "ArduinoML.structure.WriteValue"};
}
